try to compile as root on travis.ci

diff --git a/return_code/make b/return_code/make
--- a/return_code/make
+++ b/return_code/make
@@ -1,26 +1,18 @@
 #!/bin/bash
 
+function test() {
+  docker run -ti -w $(pwd) -v $(pwd):/user ubuntu:14.04 /user/$1
+  if [ $? -ne 23 ]; then
+    echo "Failed"
+    exit 1
+  fi
+}
+
 DCOMPILER=dmd ./compile -ofreturn_code.dmd return_code/return_code.d &&
-docker run -ti -w $(pwd) -v $(pwd):/user ubuntu:14.04 /user/return_code.dmd
-if [ $? -ne 23 ]; then
-  echo "Failed"
-  exit 1
-fi
-DCOMPILER=gdc ./compile -o return_code.gdc return_code/return_code.d
-docker run -ti -w $(pwd) -v $(pwd):/user ubuntu:14.04 /user/return_code.gdc
-if [ $? -ne 23 ]; then
-  echo "Failed"
-  exit 1
-fi
-DCOMPILER=ldc ./compile -ofreturn_code.ldc return_code/return_code.d
-docker run -ti -w $(pwd) -v $(pwd):/user ubuntu:14.04 /user/return_code.ldc
-if [ $? -ne 23 ]; then
-  echo "Failed"
-  exit 1
-fi
-DCOMPILER=sdc ./compile -o return_code.sdc return_code/return_code.d
-docker run -ti -w $(pwd) -v $(pwd):/user ubuntu:14.04 /user/return_code.sdc
-if [ $? -ne 23 ]; then
-  echo "Failed"
-  exit 1
-fi
+test 'return_code.dmd'
+DCOMPILER=gdc ./compile -o return_code.gdc return_code/return_code.d &&
+test 'return_code.gdc'
+DCOMPILER=ldc ./compile -ofreturn_code.ldc return_code/return_code.d &&
+test 'return_code.ldc'
+DCOMPILER=sdc ./compile -o return_code.sdc return_code/return_code.d &&
+test 'return_code.sdc'
